import { database, protect, failure } from '@/lib/server';
import { pieceSchema } from '@/lib/pieces';
export const dynamic='force-dynamic';
const parseRow=(r:any)=>({...r,images:JSON.parse(r.images)});
export async function GET(request:Request){try{const admin=new URL(request.url).searchParams.has('admin');if(admin){const denied=await protect(request);if(denied)return denied;}const sql=admin?'SELECT * FROM pieces ORDER BY updated DESC':"SELECT * FROM pieces WHERE status = 'Publicado' ORDER BY updated DESC";const {results}=await database().prepare(sql).all();return Response.json(results.map(parseRow),{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(request:Request){return save(request,false);}
export async function PUT(request:Request){return save(request,true);}
async function save(request:Request,update:boolean){try{const denied=await protect(request);if(denied)return denied;if(Number(request.headers.get('content-length')||0)>40000)return Response.json({error:'El contenido es demasiado extenso.'},{status:413});const parsed=pieceSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:parsed.error.issues[0].message},{status:400});const p=parsed.data;const id=update?p.id:crypto.randomUUID();if(!id)return Response.json({error:'Falta la pieza.'},{status:400});const args=[p.name,p.category,p.kind,p.description,p.material,p.price,p.status,p.availability,JSON.stringify(p.images),new Date().toISOString(),id];const query=update?'UPDATE pieces SET name=?,category=?,kind=?,description=?,material=?,price=?,status=?,availability=?,images=?,updated=? WHERE id=?':'INSERT INTO pieces (name,category,kind,description,material,price,status,availability,images,updated,id) VALUES (?,?,?,?,?,?,?,?,?,?,?)';const result=await database().prepare(query).bind(...args).run();if(!result.meta.changes)return Response.json({error:'La pieza ya no existe. Actualiza la página.'},{status:404});return Response.json({id});}catch(e){return failure(e);}}
export async function DELETE(request:Request){try{const denied=await protect(request);if(denied)return denied;const id=new URL(request.url).searchParams.get('id');if(!id)return Response.json({error:'Falta la pieza.'},{status:400});await database().prepare('DELETE FROM pieces WHERE id=?').bind(id).run();return Response.json({ok:true});}catch(e){return failure(e);}}
