import assert from 'node:assert/strict';

const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5173';
const password = process.env.TEST_ADMIN_PASSWORD;
if (!password) throw new Error('Set TEST_ADMIN_PASSWORD to run the authentication checks.');
const username = process.env.TEST_ADMIN_USERNAME || 'Admin';
const request = (path, options={}) => fetch(base + path, {redirect:'manual', ...options});
const login = (credentials, origin=base) => request('/api/admin/login', {method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(credentials)});

const page = await request('/admin');
assert.equal(page.status, 200);
assert.match(await page.text(), /Entrar al taller/);
assert.equal((await request('/api/pieces?admin=1')).status, 401);
assert.equal((await request('/api/photos',{method:'POST',headers:{Origin:base}})).status, 401);
assert.equal((await request('/api/pieces',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:'{}'})).status, 401);
assert.equal((await request('/api/pieces?admin=1',{headers:{Cookie:'taller_session='+'a'.repeat(64)}})).status,401);
assert.equal((await login({username,password},'https://untrusted.example')).status,403);
assert.equal((await login({username,password:'invalid-password'})).status,401);
assert.equal((await login({username:'incorrect-user',password})).status,401);
const accepted=await login({username,password});
assert.equal(accepted.status,200);
const setCookie=accepted.headers.get('set-cookie');
assert.match(setCookie,/HttpOnly/);
assert.match(setCookie,/SameSite=Strict/);
assert.match(setCookie,/Max-Age=28800/);
if(base.startsWith('https:')) assert.match(setCookie,/Secure/);
const cookie=setCookie.split(';')[0];
assert.equal((await request('/api/pieces?admin=1',{headers:{Cookie:cookie}})).status,200);
assert.match(await (await request('/admin',{headers:{Cookie:cookie}})).text(),/Tu taller, en línea/);
assert.equal((await request('/api/pieces',{method:'POST',headers:{Cookie:cookie,Origin:'https://untrusted.example'},body:'{}'})).status,403);
assert.equal((await request('/api/pieces',{method:'POST',headers:{Cookie:cookie,Origin:base,'Content-Type':'application/json'},body:'{}'})).status,400);
assert.equal((await request('/api/admin/logout',{method:'POST',headers:{Cookie:cookie,Origin:'https://untrusted.example'}})).status,403);
const logout=await request('/api/admin/logout',{method:'POST',headers:{Cookie:cookie,Origin:base}});
assert.equal(logout.status,200);
assert.match(logout.headers.get('set-cookie'),/Max-Age=0/);
assert.equal((await request('/api/pieces?admin=1',{headers:{Cookie:cookie}})).status,401,'Logged-out sessions must not be reusable');
assert.match(await (await request('/admin',{headers:{Cookie:cookie}})).text(),/Entrar al taller/);
assert.equal((await request('/api/pieces')).status,200);
console.log('Authentication checks passed: login, invalid credentials, access protection, CSRF, logout and revoked-session replay.');
