'use client';
import {useState,useEffect} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Piece,instagram} from '@/lib/pieces';
export default function Gallery(){const [items,setItems]=useState<Piece[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('Todas'),[selected,setSelected]=useState<Piece|null>(null),[photo,setPhoto]=useState(0);
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/pieces');if(!r.ok)throw new Error();setItems(await r.json() as Piece[]);}catch{setError('No pudimos cargar las piezas. Inténtalo nuevamente.');}finally{setLoading(false)}}
useEffect(()=>{void load()},[]);
return <>{loading?<p role="status">Abriendo la galería…</p>:error?<div className="error-box" role="alert">{error}<button onClick={load}>Volver a intentar</button></div>:items.length?<><div className="filter-bar">{['Todas','Anillos','Aros','Collares','Pulseras','Otros','Trabajos'].map(x=><button key={x} aria-pressed={filter===x} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="piece-grid">{items.filter(p=>filter==='Todas'||(filter==='Trabajos'?p.kind==='Trabajo':p.category===filter)).map(p=><article key={p.id}><button className="piece-button" onClick={()=>{setSelected(p);setPhoto(0)}}><img src={p.images[0]?.url} alt={p.name} loading="lazy"/><p className="eyebrow">{p.category} · {p.availability}</p><h3>{p.name}</h3><p>{p.price!==null?new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(p.price):'Descubrir la pieza'} ↗</p></button></article>)}</div>{!items.some(p=>filter==='Todas'||(filter==='Trabajos'?p.kind==='Trabajo':p.category===filter))&&<p>Aún no hay publicaciones en esta categoría.</p>}</>:<><div className="piece-grid">{[['ring-fabric.jpg','Anillos','La fuerza de un detalle'],['silver-stone.jpg','Texturas','La materia como inspiración'],['craft-process.jpg','El oficio','Historias hechas a mano']].map(([img,name,desc])=><article key={name}><img src={'/images/'+img} alt={name+' — fotografía ilustrativa'} loading="lazy"/><p className="eyebrow">REFERENCIA VISUAL</p><h3>{name}</h3><p>{desc}</p></article>)}</div><p className="reference-note">Selección ilustrativa para esta propuesta. Estas fotografías no corresponden a obras de Carolina. Fotografías de <a href="https://www.pexels.com/photo/golden-ring-under-cloth-17368718/" target="_blank" rel="noreferrer">Maryam</a>, <a href="https://www.pexels.com/photo/ring-with-gem-on-stone-16266429/" target="_blank" rel="noreferrer">Alex Lo</a> y <a href="https://www.pexels.com/photo/people-in-a-workshop-18425415/" target="_blank" rel="noreferrer">Sara Er</a> en Pexels.</p></>}
<Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="piece-dialog">{selected&&<div className="detail-grid"><div><img className="detail-main-image" src={selected.images[photo]?.url} alt={selected.images[photo]?.caption||selected.name}/>{selected.images[photo]?.caption&&<p className="detail-caption">{selected.images[photo].caption}</p>}<div className="detail-thumbs">{selected.images.map((im,i)=><button key={im.url} aria-label={'Ver fotografía '+(i+1)} aria-pressed={i===photo} onClick={()=>setPhoto(i)}><img src={im.url} alt=""/></button>)}</div></div><div className="detail-copy"><p className="eyebrow">{selected.kind} · {selected.category}</p><DialogTitle asChild><h2>{selected.name}</h2></DialogTitle><DialogDescription asChild><p className="description">{selected.description}</p></DialogDescription><div className="detail-meta">{selected.material&&<p>{selected.material}</p>}<p>{selected.availability}</p>{selected.price!==null&&<p>{new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(selected.price)}</p>}</div><a className="button dark" href={instagram} target="_blank" rel="noreferrer">Consultar con Carolina <ArrowUpRight size={17}/></a></div></div>}</DialogContent></Dialog></>}

